# format = "[:#](#ff8aae) $all"

# Makes prompt a single line
# [line_break]
# disabled = true
[package]
disabled = true

[cmd_duration]
disabled = true

# Set success and error characters
[character]
# success_symbol = "[:;](#ffc4e1)"
# error_symbol = "[:;](bold red)"
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

[hostname]
format = "[$hostname](#ff7878) in "
style = "bold red"

[username]
format = "[$user](#94b3fd) on "

# Set directory symbol
# [directory]
# truncation_length = 1
# format = "[ ï» ](bold cyan) [$path]($style)[$lock_symbol]($lock_style) "
# style = "bold cyan"
# read_only = "ğŸ”’"
# read_only_style= "bold red"

[python]
disabled = true
